version: "3"
services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: keel
      MYSQL_USER: keel
      MYSQL_PASSWORD: keel
      MYSQL_ROOT_PASSWORD: pass
