CREATE TABLE users (
  user_id bigint generated by default as identity not null primary key,
  user_name varchar(50),
  version_no bigint default 1
);

insert into users (user_name, version_no) values ('test', 1);
